# Generated by Django 4.0.4 on 2022-06-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_rename_region_perfil_usuario_region_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil_usuario',
            options={'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
        migrations.RemoveField(
            model_name='perfil_usuario',
            name='region',
        ),
        migrations.AddField(
            model_name='perfil_usuario',
            name='apellido',
            field=models.CharField(default='nn', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil_usuario',
            name='nombre',
            field=models.CharField(default='nn', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil_usuario',
            name='imagen_perfil',
            field=models.ImageField(default='media/imagen_perfil/perfil_sin_foto.png', upload_to='imagen_perfil'),
        ),
    ]
