# Generated by Django 4.0.4 on 2022-06-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_perfil_usuario_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil_usuario',
            name='imagen_perfil',
            field=models.ImageField(default='imagen_perfil/perfil_sin_foto.png', upload_to='imagen_perfil'),
        ),
    ]
