# Generated by Django 4.0.4 on 2022-06-23 23:42

from django.db import migrations, models
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_perfil_usuario_imagen_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil_usuario',
            name='imagen_perfil',
            field=models.ImageField(default='imagen_perfil/perfil_sin_foto.png', upload_to=usuarios.models.user_directory_path),
        ),
    ]
