# Generated by Django 4.0.4 on 2022-06-25 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0007_perfil_usuario_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil_usuario',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='perfil_usuario',
            name='email',
        ),
        migrations.RemoveField(
            model_name='perfil_usuario',
            name='nombre',
        ),
        migrations.AddField(
            model_name='perfil_usuario',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfil_usuario',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
