# Generated by Django 4.0.4 on 2022-06-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_remove_perfil_usuario_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil_usuario',
            name='imagen_perfil',
            field=models.ImageField(default='imagen_perfil/perfil_sin_foto.png', upload_to='imagen_perfil'),
        ),
    ]
