# Generated by Django 4.0.4 on 2022-06-25 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_alter_perfil_usuario_imagen_perfil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil_usuario',
            options={'verbose_name': 'perfil', 'verbose_name_plural': 'perfiles'},
        ),
    ]
