# Generated by Django 4.0.4 on 2022-06-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppNQV', '0004_plataformas_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actores',
            options={'verbose_name': 'actor', 'verbose_name_plural': 'actores'},
        ),
        migrations.AlterModelOptions(
            name='peliculas',
            options={'verbose_name': 'pelicula', 'verbose_name_plural': 'peliculas'},
        ),
        migrations.AlterModelOptions(
            name='plataformas',
            options={'verbose_name': 'plataforma', 'verbose_name_plural': 'plataformas'},
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='duracion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
