# Generated by Django 4.0.4 on 2022-06-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppNQV', '0005_alter_actores_options_alter_peliculas_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actores',
            name='fechaDeNacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='fechaDeEstreno',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de estreno'),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='linkTrailer',
            field=models.URLField(blank=True, null=True, verbose_name='Link Trailer'),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='ratingIMDB',
            field=models.FloatField(blank=True, null=True, verbose_name='Rating IMDB'),
        ),
        migrations.AlterField(
            model_name='plataformas',
            name='cantidadPeliculasDisponibles',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad de peliculas disponibles'),
        ),
        migrations.AlterField(
            model_name='plataformas',
            name='cantidadUsuarios',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad de Usuarios'),
        ),
        migrations.AlterField(
            model_name='plataformas',
            name='precioSuscripcion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Precio de suscripcion'),
        ),
    ]
