# Generated by Django 4.0.4 on 2022-06-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppNQV', '0006_alter_actores_fechadenacimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actores',
            name='imagen_actores',
            field=models.ImageField(blank=True, null=True, upload_to='actores', verbose_name='Imagen Actores'),
        ),
        migrations.AddField(
            model_name='peliculas',
            name='imagen_peliculas',
            field=models.ImageField(blank=True, null=True, upload_to='peliculas', verbose_name='Imagen Pelicula'),
        ),
        migrations.AddField(
            model_name='plataformas',
            name='imagen_plataformas',
            field=models.ImageField(blank=True, null=True, upload_to='plataformas', verbose_name='Imagen Plataformas'),
        ),
    ]
