# Generated by Django 4.0.4 on 2022-06-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppNQV', '0007_actores_imagen_actores_peliculas_imagen_peliculas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plataformas',
            name='cantidadSeriesDisponibles',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad de series disponibles'),
        ),
    ]
