# Generated by Django 4.0.4 on 2022-06-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppNQV', '0008_plataformas_cantidadseriesdisponibles'),
    ]

    operations = [
        migrations.AddField(
            model_name='plataformas',
            name='linkPlataforma',
            field=models.URLField(blank=True, null=True, verbose_name='Link Plataforma'),
        ),
    ]
