# Generated by Django 4.0.4 on 2022-06-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppNQV', '0010_alter_plataformas_linkplataforma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plataformas',
            name='linkPlataforma',
            field=models.URLField(blank=True, null=True, verbose_name='Link Plataforma'),
        ),
    ]
