# Generated by Django 4.0.4 on 2022-06-25 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppNQV', '0011_alter_plataformas_linkplataforma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plataformas',
            name='imagen_plataformas',
            field=models.FileField(blank=True, null=True, upload_to='plataformas', verbose_name='Imagen Plataformas'),
        ),
    ]
