# Generated by Django 4.0.4 on 2022-06-26 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppNQV', '0013_alter_plataformas_imagen_plataformas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actores',
            name='imagen_actores',
            field=models.ImageField(default='cinema-vector.jpg', upload_to='actores', verbose_name='Imagen Actores'),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='imagen_peliculas',
            field=models.ImageField(default='cinema-vector.jpg', upload_to='peliculas', verbose_name='Imagen Pelicula'),
        ),
        migrations.AlterField(
            model_name='plataformas',
            name='imagen_plataformas',
            field=models.ImageField(default='cinema-vector.jpg', upload_to='plataformas', verbose_name='Imagen Plataformas'),
        ),
    ]
