# Generated by Django 4.0.4 on 2022-06-27 23:45

import AppNQV.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppNQV', '0014_alter_actores_imagen_actores_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peliculas',
            name='oscar',
        ),
        migrations.AddField(
            model_name='peliculas',
            name='year',
            field=models.IntegerField(default=AppNQV.models.current_year, validators=[django.core.validators.MinValueValidator(1984), AppNQV.models.max_value_current_year], verbose_name='año'),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='clasificacion',
            field=models.CharField(choices=[('accion', 'ACCION'), ('animada', 'ANIMADA'), ('biografica', 'BIOGRAFICA'), ('comedia', 'COMEDIA'), ('crimen', 'CRIMEN'), ('documental', 'DOCUMENTAL'), ('drama', 'DRAMA'), ('romantica', 'ROMANTICA'), ('suspenso', 'SUSPENSO'), ('terror', 'TERROR')], default='drama', max_length=20),
        ),
    ]
