# Generated by Django 4.0.4 on 2022-06-28 00:09

import AppNQV.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppNQV', '0015_remove_peliculas_oscar_peliculas_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='year',
            field=models.IntegerField(default=AppNQV.models.current_year, validators=[django.core.validators.MinValueValidator(1900), AppNQV.models.max_value_current_year], verbose_name='año'),
        ),
    ]
